spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ulutman


jwt:
  secret: localdevsecretkey_at_least_32_characters_long_for_hs256

minio:
  url: https://fly.storage.tigris.dev
  access-key: tid_dT_HHHrvCoE_FTBxQ_iuEuSNDoRceWarFoOLjSSvTmoGZQmqYh
  secret-key: tsec_C-_2OI2PCNp7VA--uptW+tSOfvrb6ua_77e7VagQ-arXC+lv-2JAbLlJV1fp9F_z+K6q_a
  bucket: ulutman-images
  region: auto