spring:
  application:
    name: ulutman

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

server:
  port: 8080
  ssl:
    enabled: false
  forward-headers-strategy: native

springdoc:
  swagger-ui:
    url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}

minio:
  url: ${AWS_ENDPOINT_URL:https://fly.storage.tigris.dev}
  access-key: ${AWS_ACCESS_KEY_ID:changeme}
  secret-key: ${AWS_SECRET_ACCESS_KEY:changeme}
  bucket: ${AWS_S3_BUCKET_NAME:ulutman-images}
  region: ${AWS_DEFAULT_REGION:auto}
